// Widget modules migrated to the Makepad 2.0 script_mod! API.

pub mod accordion;
pub mod alert;
pub mod avatar;
pub mod badge;
pub mod breadcrumb;
pub mod button;
pub mod calendar;
pub mod card;
pub mod checkbox;
pub mod chip;
pub mod collapsible;
pub mod control_bar;
pub mod combobox;
pub mod command;
pub mod context_menu;
pub mod dialog;
pub mod divider;
pub mod dropdown_menu;
pub mod dropdown;
pub mod empty_state;
pub mod focus;
pub mod hover_card;
pub mod input;
pub mod kbd;
pub mod label;
pub mod link;
pub mod list;
pub mod modal;
pub mod menu_bar;
pub mod notification;
pub mod orb;
pub mod page_flip;
pub mod pagination;
pub mod popover;
pub mod progress;
pub mod progress_ring;
pub mod radio;
pub mod rating;
pub mod select;
pub mod separator;
pub mod scroll_area;
pub mod sheet;
pub mod skeleton;
pub mod option_card;
pub mod stat_card;
pub mod slider;
pub mod split_pane;
pub mod spinner;
pub mod stepper;
pub mod switch;
pub mod tab;
pub mod table;
pub mod text;
pub mod textarea;
pub mod theme_state;
pub mod toggle;
pub mod scaffolding;
pub mod status;
pub mod toggle_group;
pub mod tooltip;
pub mod tree;

pub use accordion::*;
pub use alert::*;
pub use avatar::*;
pub use badge::*;
pub use breadcrumb::*;
pub use button::*;
pub use calendar::*;
pub use card::*;
pub use checkbox::*;
pub use chip::*;
pub use collapsible::*;
pub use control_bar::*;
pub use combobox::*;
pub use command::*;
pub use context_menu::*;
pub use dialog::*;
pub use divider::*;
pub use dropdown_menu::*;
pub use empty_state::*;
pub use focus::*;
pub use hover_card::*;
pub use input::*;
pub use kbd::*;
pub use label::*;
pub use link::*;
pub use modal::*;
pub use menu_bar::*;
pub use notification::*;
pub use orb::*;
pub use page_flip::*;
pub use pagination::*;
pub use popover::*;
pub use progress::*;
pub use progress_ring::*;
pub use radio::*;
pub use rating::*;
pub use select::*;
pub use scroll_area::*;
pub use sheet::*;
pub use skeleton::*;
pub use option_card::*;
pub use scaffolding::*;
pub use status::*;
pub use stat_card::*;
pub use slider::*;
pub use split_pane::*;
pub use spinner::*;
pub use stepper::*;
pub use switch::*;
pub use tab::*;
pub use table::*;
pub use text::*;
pub use textarea::*;
pub use theme_state::*;
pub use toggle::*;
pub use toggle_group::*;
pub use tooltip::*;
pub use tree::*;
// dropdown, list are style-only (pure script_mod!, no Rust struct)

use makepad_widgets::*;

pub fn script_mod(vm: &mut ScriptVm) {
    crate::widgets::accordion::script_mod(vm);
    crate::widgets::alert::script_mod(vm);
    crate::widgets::calendar::script_mod(vm);
    crate::widgets::avatar::script_mod(vm);
    crate::widgets::badge::script_mod(vm);
    crate::widgets::breadcrumb::script_mod(vm);
    crate::widgets::button::script_mod(vm);
    crate::widgets::card::script_mod(vm);
    crate::widgets::checkbox::script_mod(vm);
    crate::widgets::chip::script_mod(vm);
    crate::widgets::collapsible::script_mod(vm);
    crate::widgets::control_bar::script_mod(vm);
    crate::widgets::command::script_mod(vm);
    crate::widgets::dialog::script_mod(vm);
    crate::widgets::divider::script_mod(vm);
    crate::widgets::dropdown::script_mod(vm);
    crate::widgets::hover_card::script_mod(vm);
    crate::widgets::empty_state::script_mod(vm);
    crate::widgets::input::script_mod(vm);
    crate::widgets::combobox::script_mod(vm);
    crate::widgets::kbd::script_mod(vm);
    crate::widgets::context_menu::script_mod(vm);
    crate::widgets::dropdown_menu::script_mod(vm);
    crate::widgets::label::script_mod(vm);
    crate::widgets::link::script_mod(vm);
    crate::widgets::list::script_mod(vm);
    crate::widgets::modal::script_mod(vm);
    crate::widgets::menu_bar::script_mod(vm);
    crate::widgets::notification::script_mod(vm);
    crate::widgets::orb::script_mod(vm);
    crate::widgets::page_flip::script_mod(vm);
    crate::widgets::pagination::script_mod(vm);
    crate::widgets::popover::script_mod(vm);
    crate::widgets::progress::script_mod(vm);
    crate::widgets::progress_ring::script_mod(vm);
    crate::widgets::radio::script_mod(vm);
    crate::widgets::rating::script_mod(vm);
    crate::widgets::select::script_mod(vm);
    crate::widgets::separator::script_mod(vm);
    crate::widgets::scroll_area::script_mod(vm);
    crate::widgets::sheet::script_mod(vm);
    crate::widgets::skeleton::script_mod(vm);
    crate::widgets::stat_card::script_mod(vm);
    crate::widgets::slider::script_mod(vm);
    crate::widgets::split_pane::script_mod(vm);
    crate::widgets::spinner::script_mod(vm);
    crate::widgets::stepper::script_mod(vm);
    crate::widgets::switch::script_mod(vm);
    crate::widgets::tab::script_mod(vm);
    crate::widgets::table::script_mod(vm);
    crate::widgets::text::script_mod(vm);
    crate::widgets::textarea::script_mod(vm);
    crate::widgets::theme_state::script_mod(vm);
    crate::widgets::toggle::script_mod(vm);
    crate::widgets::toggle_group::script_mod(vm);
    crate::widgets::option_card::script_mod(vm);
    crate::widgets::scaffolding::script_mod(vm);
    crate::widgets::status::script_mod(vm);
    crate::widgets::tooltip::script_mod(vm);
    crate::widgets::tree::script_mod(vm);
}
