// Widget modules migrated to the Makepad 2.0 script_mod! API.

pub mod accordion;
pub mod alert;
pub mod avatar;
pub mod badge;
pub mod breadcrumb;
pub mod button;
pub mod calendar;
pub mod card;
pub mod checkbox;
pub mod collapsible;
pub mod command;
pub mod dialog;
pub mod divider;
pub mod dropdown;
pub mod hover_card;
pub mod input;
pub mod label;
pub mod link;
pub mod list;
pub mod modal;
pub mod notification;
pub mod page_flip;
pub mod pagination;
pub mod popover;
pub mod progress;
pub mod radio;
pub mod select;
pub mod separator;
pub mod sheet;
pub mod skeleton;
pub mod slider;
pub mod spinner;
pub mod switch;
pub mod tab;
pub mod text;
pub mod textarea;
pub mod toggle;
pub mod tooltip;

pub use accordion::*;
pub use alert::*;
pub use avatar::*;
pub use badge::*;
pub use breadcrumb::*;
pub use button::*;
pub use calendar::*;
pub use card::*;
pub use checkbox::*;
pub use collapsible::*;
pub use command::*;
pub use dialog::*;
pub use divider::*;
pub use hover_card::*;
pub use input::*;
pub use label::*;
pub use link::*;
pub use modal::*;
pub use notification::*;
pub use page_flip::*;
pub use pagination::*;
pub use popover::*;
pub use progress::*;
pub use radio::*;
pub use select::*;
pub use sheet::*;
pub use skeleton::*;
pub use slider::*;
pub use spinner::*;
pub use switch::*;
pub use tab::*;
pub use text::*;
pub use textarea::*;
pub use toggle::*;
pub use tooltip::*;
// dropdown, list are style-only (pure script_mod!, no Rust struct)

use makepad_widgets::*;

pub fn script_mod(vm: &mut ScriptVm) {
    crate::widgets::accordion::script_mod(vm);
    crate::widgets::alert::script_mod(vm);
    crate::widgets::calendar::script_mod(vm);
    crate::widgets::avatar::script_mod(vm);
    crate::widgets::badge::script_mod(vm);
    crate::widgets::breadcrumb::script_mod(vm);
    crate::widgets::button::script_mod(vm);
    crate::widgets::card::script_mod(vm);
    crate::widgets::checkbox::script_mod(vm);
    crate::widgets::collapsible::script_mod(vm);
    crate::widgets::command::script_mod(vm);
    crate::widgets::dialog::script_mod(vm);
    crate::widgets::divider::script_mod(vm);
    crate::widgets::dropdown::script_mod(vm);
    crate::widgets::hover_card::script_mod(vm);
    crate::widgets::input::script_mod(vm);
    crate::widgets::label::script_mod(vm);
    crate::widgets::link::script_mod(vm);
    crate::widgets::list::script_mod(vm);
    crate::widgets::modal::script_mod(vm);
    crate::widgets::notification::script_mod(vm);
    crate::widgets::page_flip::script_mod(vm);
    crate::widgets::pagination::script_mod(vm);
    crate::widgets::popover::script_mod(vm);
    crate::widgets::progress::script_mod(vm);
    crate::widgets::radio::script_mod(vm);
    crate::widgets::select::script_mod(vm);
    crate::widgets::separator::script_mod(vm);
    crate::widgets::sheet::script_mod(vm);
    crate::widgets::skeleton::script_mod(vm);
    crate::widgets::slider::script_mod(vm);
    crate::widgets::spinner::script_mod(vm);
    crate::widgets::switch::script_mod(vm);
    crate::widgets::tab::script_mod(vm);
    crate::widgets::text::script_mod(vm);
    crate::widgets::textarea::script_mod(vm);
    crate::widgets::toggle::script_mod(vm);
    crate::widgets::tooltip::script_mod(vm);
}
